try:
    a=5
    a+'10'
except Exception:
    print('exception handled')